### PR TITLE
Fixed the initialize function

### LINKED ISSUE #10: Initialized values are not reset on calling initialize again
The following properties are not reset if the initialize method is called again. Consider the following scenario:

```
ApiConnector::initialize(
    'key',
    'secret',
    $endpoint = 'https://app.penneo.com/api/v1',
    $user = 1,
    $headers = ['Content-type' => 'application/x-www-form-urlencoded']
);
```

Now we initialize the api connector again:

```
ApiConnector::initialize(
    'key',
    'secret'
  );
```

Now the `$endpoint`, `$user`, and the `$headers` are not reset

### PR DESCRIPTION
**Pull request by ahmadnazir**
Fixes #10

### CODE REVIEW

File: src/ApiConnector.php [hunk 1]
```diff
@@ -21,15 +30,21 @@ class ApiConnector
...
+		if ($headers) {
 			self::$headers = array_merge($headers, self::$headers);
-		if ($user)
+		}
+
+		if ($user) {
 			self::$headers['penneo-api-user'] = intval($user);
-		
+		} else {
+			unset(self::$headers['penneo-api-user']);
```
Comment (janflora) [inline src/ApiConnector.php]: This else section is not really needed since you overwrote any previous headers in line 37.

**Comment by janflora** [comment]
The changes have been reviewed and approved.

File: src/ApiConnector.php (hunk 1 above)
Comment (ahmadnazir) [inline src/ApiConnector.php]: Good point. Fixed now.
